apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-0-service
spec:
  type: NodePort
  selector:
    app: kafka-broker-0
  ports:
    - name: internal
      port: 29092
      targetPort: 29092
    - name: external
      port: 9092
      targetPort: 9092
      nodePort: 32001
