apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-1-service
spec:
  type: NodePort
  selector:
    app: kafka-broker-1
  ports:
    - name: internal
      port: 29093
      targetPort: 29093
    - name: external
      port: 9093
      targetPort: 9093
      nodePort: 32002
