apiVersion: v1
kind: Service
metadata:
  name: kafka-broker-2-service
spec:
  type: NodePort
  selector:
    app: kafka-broker-2
  ports:
    - name: internal
      port: 29094
      targetPort: 29094
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 32003
